# Generated by Django 5.0.6 on 2024-07-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0002_client_mechanic_vehicle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={"ordering": ("model",)},
        ),
    ]
