# Generated by Django 5.0.6 on 2024-07-24 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0004_alter_client_options_alter_mechanic_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="managed_vehicles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
